### ISSUE TITLE
Rejections are not propagated

### ISSUE THREAD

**Issue by kraih** [stevan/promises-perl#73]
I've been stealing some of the internal design of `Promises` for `Mojolicious`, and noticed that rejections are not propagated through the promise chain. It looks like [this line](https://github.com/stevan/promises-perl/blob/a2fc867583d0849e762a94431dd7e129ce106392/lib/Promises/Deferred.pm#L195) should be `$d->$method(@results);` instead of `$d->resolve(@results);`.

You can test this by chaining multiple `->catch(sub {...})` calls. Propagating rejections is a requirement of [Promises/A+](https://promisesaplus.com/).

**Comment by kraih** [comment]
My bad, looks like i misunderstood the spec.

**Comment by yanick** [comment]
Heh. :-)
