### ISSUE TITLE
collect() eats 100% cpu when called without arguments

### ISSUE THREAD

**Issue by ehuelsmann** [stevan/promises-perl#82]
While I do understand this isn't the intended use-case, this code triggered the above condition for me:

```perl
    collect(map { $_->validate() } @resources)
    ->then(sub { call_after_all_finished(); });
```

Where each `validate()` method returns a promise, but `@resources` was empty. I'm not interested in the values to which the promises resolve; basically, they're only used to wait for all actions to be completed before going to the final step.

**Comment by ehuelsmann** [comment]
If that's appreciated, I could submit a PR.

**Comment by yanick** [comment]
[PRs welcome] Absolutely!

**Comment by ehuelsmann** [comment]
thanks for the fix! I couldn't have solved it more elegantly!

**Comment by yanick** [comment]
New release should be out in a matter of hours!
