### ISSUE TITLE
README.md references nonexistent Makefile.PL

### ISSUE THREAD

**Issue by brianwisti** [stevan/promises-perl#89]
Tried building from a fresh git checkout to look more closely at #88 , but the `Makefile.PL` mentioned in `README.md` is not present. That might be me confusing user documentation with developer documentation, but maybe a note for what explorers & potential contributors need to do?

**Comment by yanick** [comment]
Ah yes. The Makefile.PL is produced by Dist::Zilla. It can be seen in the `releases` branch, but is not seen in `master`. I'll update the docs to give a fair chance to newcomes. Thanks!
